{% set name = "django-tenant-schemas" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-tenant-schemas-{{ version }}.tar.gz
  sha256: 0fde4e9600e695e02adf120ea2be24f19df990cc47c6b8cb0fa169c98557430d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2
    - ordered-set
    - psycopg2-binary
    - six

test:
  imports:
    - tenant_schemas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bcarneiro/django-tenant-schemas
  summary: Tenant support for Django using PostgreSQL schemas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
