{% set name = "django-tenant-schemas" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5696fab7090b00e6b4935cd37f4581ee9d3914f0d838306149c84fd4cf6624cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2
    - ordered-set
    - psycopg2-binary
    - six

test:
  imports:
    - tenant_schemas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bcarneiro/django-tenant-schemas
  summary: Tenant support for Django using PostgreSQL schemas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
